### ISSUE TITLE
Убрать автонастройку canvas при смене размера/формата окна

### ISSUE THREAD

**Issue by Snake5932** [bmstu-iu9/utp2020-3-2d-game#5]

**Comment by Mazdaywik** [comment]
И по какой причине закрыли?

**Comment by frussian** [comment]
> И по какой причине закрыли?

У нас сначала карта была во все окно вкладки, но потом было принято решение сделать ее квадратной, не во весь экран и остался старый код, который был не нужен и я его удалил. Сейчас размер карты не меняется.
